name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is stale because it has been open for 365 days with no activity. Remove the `stale` label or comment or this will be closed in 60 days'
        stale-pr-message: 'This pull request is stale because it has been open 365 days with no activity. Remove the `stale` label or comment on this issue, or it will be closed in 60 days'
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
        days-before-stale: 365
        days-before-close: 60
        exempt-issue-label: 'pinned'
        exempt-pr-label: 'pinned'
